apiVersion: v1
kind: Service
metadata:
  name: inspireme-service
spec:
  type: NodePort
  selector:
    app: inspireme
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007  # Exposed on this port
