name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/inspireme:${{github.run_id}}

  update-k8s-manifest:
    runs-on: ubuntu-latest
    needs: docker-build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Update image tag in Kubernetes manifest
        run: |
          sed -i "s|image: .*$|image: ${{ secrets.DOCKER_USERNAME }}/inspireme:${{ github.run_id }}|" k8s/deploy.yml

      - name: Commit and push updated manifest
        run: |
          git config --global user.email "manuelokororie@gmail.com"
          git config --global user.name "Emmanuel Okororie"
          git add k8s/deploy.yml
          git commit -m "[CI]: Update Kubernetes manifest with image tag ${{ github.run_id }}"
          git push origin HEAD:main
